// <auto-generated />
using System;
using Freelancer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Freelancer.Migrations
{
    [DbContext(typeof(MvcFreelancerContext))]
    [Migration("20210113113204_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Freelancer.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cat_Id")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("Text")
                        .HasColumnName("cat_description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cat_Nom");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Freelancer.Models.Clients", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id")
                        .UseIdentityColumn();

                    b.Property<int>("CatId")
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Freelancer.Models.Devis", b =>
                {
                    b.Property<int>("DevisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("devis_id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("devis_date");

                    b.Property<DateTime>("DevisDateFinale")
                        .HasColumnType("datetime2")
                        .HasColumnName("devis_date_finale");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("devis_etat");

                    b.Property<int>("MissionId")
                        .HasColumnType("int")
                        .HasColumnName("mission_id");

                    b.Property<int>("Montant")
                        .HasColumnType("int")
                        .HasColumnName("devis_montant");

                    b.Property<int>("MontantFinal")
                        .HasColumnType("int")
                        .HasColumnName("devis_montant_final");

                    b.HasKey("DevisId");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("Freelancer.Models.Missions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mission_id")
                        .UseIdentityColumn();

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("datetime2")
                        .HasColumnName("mission_debut");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("mission_description");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("mission_etat");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2")
                        .HasColumnName("mission_fin");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mission_titre");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });
#pragma warning restore 612, 618
        }
    }
}
